# C++ project
language: cpp
sudo: required
dist: xenial
install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install libboost-dev libboost-serialization-dev gdal-bin libgdal-dev make cmake
  - sudo apt-get -y install libbz2-dev libexpat1-dev swig python-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j 4
  - ./fmm
  - ./stmatch
  - ./ubodt_gen
  - export PYTHONPATH=${PYTHONPATH}:$(pwd)/python
  - cd ../example/python
  - python fmm_test.py
branches:
  only:
  - master
  - osm
